# Generated by Django 4.2 on 2023-07-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=14)),
                ('country', models.CharField(max_length=10)),
                ('approximated_budget', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=14)),
                ('details', models.TextField()),
                ('service_type', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('postion', models.CharField(max_length=15)),
                ('how_did_you_know_us', models.CharField(max_length=15)),
                ('file', models.FileField(upload_to='uploadFiles/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Quotea',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'Testimonials'},
        ),
    ]
