# Generated by Django 4.2 on 2023-07-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_quote_alter_testimonial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'Quotes'},
        ),
    ]
